# Generated by Django 4.1.3 on 2022-11-04 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('height', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winter', models.CharField(max_length=255)),
                ('summer', models.CharField(max_length=255)),
                ('autumn', models.CharField(max_length=255)),
                ('spring', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('fam', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('otc', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='pereval_added',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beautyTitle', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('other_titles', models.CharField(max_length=255)),
                ('connect', models.CharField(max_length=255)),
                ('add_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('Добавлено', 'Добавлено'), ('Рассматривается', 'Рассматривается'), ('Принято', 'Принято'), ('Отклонено', 'Отклонено')], default='Добавлено', max_length=255)),
                ('coords', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turapps.coords')),
                ('images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turapps.images')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turapps.level')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turapps.users')),
            ],
        ),
    ]
