# Generated by Django 4.1.3 on 2022-11-04 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turapps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pereval_added',
            name='coords',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='per_coords', to='turapps.coords'),
        ),
        migrations.AlterField(
            model_name='pereval_added',
            name='images',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='per_images', to='turapps.images'),
        ),
        migrations.AlterField(
            model_name='pereval_added',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='per_level', to='turapps.level'),
        ),
        migrations.AlterField(
            model_name='pereval_added',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='per_user', to='turapps.users'),
        ),
    ]
