# Generated by Django 4.1.3 on 2022-11-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turapps', '0005_alter_users_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=255),
        ),
    ]
